steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-api-instance', '-f', './test-bench/flask-api/Dockerfile', './test-bench']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-api-instance']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'delete', 'flask-api', '--project=bdspro', '--zone=europe-west3-a', '--quiet']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create-with-container', 'flask-api',
         '--project=$PROJECT_ID', '--zone=europe-west3-a', '--container-image=gcr.io/$PROJECT_ID/flask-api-instance', '--machine-type=f1-micro', '--scopes=cloud-platform']