steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sink-instance', '-f', 'sink/Dockerfile', './sink']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sink-instance']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'delete', 'sink', '--project=bdspro', '--zone=europe-west3-a', '--quiet']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create-with-container', 'sink',
         '--project=$PROJECT_ID', '--zone=europe-west3-a', '--container-image=gcr.io/$PROJECT_ID/sink-instance', '--machine-type=e2-micro', '--scopes=cloud-platform', '--network-interface=private-network-ip=10.156.0.56,subnet=default']