steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/tipa12/unikernel-BDSProj.git', '--branch', 'tpabst_deployTupleGeneratoToComputeEngine']
  availableSecrets:
    secretManager:
    - versionName: projects/bdspro/secrets/githubsecret/versions/1
    env: '_GITHUB_TOKEN'

- name: 'python:3.8'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt']

#- name: 'python:3.8'
#  entrypoint: 'python'
#  args: ['-m', 'pytest', 'tests/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create', 'DataService', '--zone', 'europe-west3-a', '--machine-type', 'e2-small', '--image-family', 'ubuntu-2004-lts', '--image-project', 'ubuntu-os-cloud']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--zone', 'europe-west3-a', './main.py', './tupleGenerator.py', 'DataService:~/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'DataService', '--zone', 'europe-west3-a', '--command', 'python3 <PROGRAM_NAME>.py']
