steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['components', 'update']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'delete', 'dataservice', '--zone', 'europe-west3-a', '--quiet']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create', 'dataservice', '--service-account', 'bdspro@appspot.gserviceaccount.com', '--scopes', 'cloud-platform', '--zone', 'europe-west3-a', '--machine-type', 'e2-micro', '--image-family', 'ubuntu-2204-lts', '--image-project', 'ubuntu-os-cloud']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '--zone', 'europe-west3-a', 'dataService/main.py', 'dataService/tupleGenerator.py', 'dataService/requirements.txt', 'dataService/start.sh', 'dataservice:~/']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'chmod +x start.sh']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'sudo apt update -y']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'sudo apt install -y python3-pip']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'pip3 install -r requirements.txt']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'nohup python3 -m main.py &']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'add-metadata', 'dataService', '--metadata-from-file', 'startup-script=start.sh']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'sudo reboot']

#availableSecrets:
#  secretManager:
#  - versionName: projects/bdspro/secrets/githubsecret/versions/latest
#    env: 'GITHUB_TOKEN'
