steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', "https://$$GITHUB_TOKEN@github.com/tipa12/unikernel-BDSProj.git", '--branch', 'tpabst_deployTupleGeneratoToComputeEngine', '--single-branch', '--depth', '1']
#  secretEnv: ['GITHUB_TOKEN']
- name: 'python:3.8'
  entrypoint: 'pip'
  args: ['install', '-r', 'dataService/requirements.txt']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'instances', 'delete', 'dataservice', '--zone', 'europe-west3-a']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['components', 'update']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'delete', 'dataservice', '--zone', 'europe-west3-a']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create', 'dataservice', '--zone', 'europe-west3-a', '--machine-type', 'e2-micro', '--image-family', 'ubuntu-2204-lts', '--image-project', 'ubuntu-os-cloud']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--zone', 'europe-west3-a', 'dataService/main.py', 'dataService/tupleGenerator.py', 'dataService/requirements.txt', 'dataservice:~/']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'scp', '--zone', 'europe-west3-a', './main.py', './tupleGenerator.py', './requirements.txt', 'dataservice:~/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'sudo apt update -y']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'sudo apt install -y python3-pip']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'pip3 install -r requirements.txt']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'python3 main.py']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'dataservice', '--zone', 'europe-west3-a', '--command', 'gunicorn -w 4 -b 0.0.0.0:8000 main']


#availableSecrets:
#  secretManager:
#  - versionName: projects/bdspro/secrets/githubsecret/versions/latest
#    env: 'GITHUB_TOKEN'
