###
### General configuration
###
# logLevel: LOG_ERROR
#logLevel: LOG_WARNING
logLevel: LOG_DEBUG
optimizer:
  distributedWindowChildThreshold: 3

###
### Network configuration
###
restIp: 10.142.0.32
coordinatorIp: 10.142.0.32
restPort: 80

###
### Logical source configuration
###
logicalSources:
  - logicalSourceName: "input_tuple"
    fields:
      - name: a
        type: INT64
      - name: b
        type: INT64
      - name: c
        type: INT64
      - name: d
        type: INT64
      - name: e
        type: INT64
      - name: f
        type: INT64

              
