###
### General configuration
###
# logLevel: LOG_ERROR
logLevel: LOG_WARNING
# logLevel: LOG_DEBUG
optimizer:
        distributedWindowChildThreshold: 3

###
### Network configuration
###
restIp: 10.142.0.32
coordinatorIp: 10.142.0.32
restPort: 80

###
### Logical source configuration
###
logicalSources:
        - logicalSourceName: "wind_turbines_mqtt"
          fields:
              - name: a
                type: INT32
              - name: b
                type: INT32
              - name: c
                type: INT32
              - name: d
                type: INT32
              - name: e
                type: INT32
        - logicalSourceName: "wind_turbines_csv"
          fields:
              - name: a
                type: INT32
              - name: b
                type: INT32
              - name: c
                type: INT32
              - name: d
                type: INT32
              - name: e
                type: INT32      
              
