###
### General configuration
###
# logLevel: LOG_ERROR
#logLevel: LOG_TRACE
logLevel: LOG_DEBUG

###
### Network configuration
###
localWorkerIp: 10.142.0.34
coordinatorIp: 10.142.0.32

###
### Physical source configuration
###
physicalSources:
        - logicalSourceName: wind_turbines_mqtt
          physicalSourceName: wind_turbine_2
          type: MQTTSource
          configuration:
                topic: /wind_turbines
                cleanSession: true
                clientId: rfRqLGZRChg8eS30PEeR
                flushIntervalMS: 300
                inputFormat: JSON
                url: "ws://10.142.0.36:9001"
                qos: 2
                userName: rfRqLGZRChg8eS30PEeR
