###
### General configuration
###
logLevel: LOG_ERROR
#logLevel: LOG_TRACE
#logLevel: LOG_DEBUG

###
### Network configuration
###
localWorkerIp: 10.150.0.34
coordinatorIp: 10.142.0.32

###
### Physical source configuration
###
physicalSources:
  - logicalSourceName: input_tuple
    physicalSourceName: tcp_source
    type: TCPSource
    configuration:
      socketHost: 10.142.0.36
      socketPort: 8081
      socketDomain: AF_INET
      socketType: SOCK_STREAM
      flushIntervalMS: 1
      inputFormat: JSON
      decideMessageSize: TUPLE_SEPARATOR
      tupleSeparator: '|'
